# Generated by Django 3.2.7 on 2021-09-09 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data_Store',
            fields=[
                ('user_key', models.CharField(max_length=450, primary_key=True, serialize=False)),
                ('data', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='Key_Store',
            fields=[
                ('username', models.CharField(max_length=450, primary_key=True, serialize=False)),
                ('public_key', models.CharField(max_length=450)),
            ],
        ),
    ]
